export interface DailyVerseEntry {
  book: string;
  chapter: string;
  verse: string;
  category: string;
  referenceAm?: string;
  textAm?: string;
}

/**
 * Curated list of Bible verses for daily rotation.
 * Day of year (1-365) is used as index (modulo array length).
 * Mix of categories: Salvation, Strength, Comfort, Faith, Love, Hope, Healing.
 */
export const dailyVerses: DailyVerseEntry[] = [
  { book: 'john', chapter: '3', verse: '16', category: 'Salvation', referenceAm: 'ዮሐንስ 3:16', textAm: 'እግዚአብሔር ዓለሙን እንዲያፍር እስከ መሐረው አንዱን ልጁን ሰጠ፤ በእርሱ የሚያምን ሁሉ እንዳይጠፋ ዘላለማዊ ሕይወት እንዲኖረው።' },
  { book: 'psalms', chapter: '23', verse: '1', category: 'Comfort', referenceAm: 'መዝሙረ ዳዊት 23:1', textAm: 'እግዚአብሔር መሰኛዬ ነው፤ ወደ እርሱ ደግሞ አልጎድልም።' },
  { book: 'philippians', chapter: '4', verse: '13', category: 'Strength', referenceAm: 'ፊልጵስዩስ 4:13', textAm: 'የሚያበርትኝ ሁሉ በክርስቶስ በኩል ደግሞ እችላለሁ።' },
  { book: 'jeremiah', chapter: '29', verse: '11', category: 'Hope', referenceAm: 'ኤርምያስ 29:11', textAm: 'እኔ ስለ እናንተ ያሰብኋቸው ዐሳብ ሰላምን ይሰጣል እንጂ ክፉን አይደለም፤ ተስፋ ያለውን የወደፊት ይሰጣችኋል።' },
  { book: 'proverbs', chapter: '3', verse: '5', category: 'Faith', referenceAm: 'ምሳሌ 3:5', textAm: 'በልብህ በሙሉ በእግዚአብሔር ተመካ፤ በማስተዋልህም አትመካ።' },
  { book: 'romans', chapter: '8', verse: '28', category: 'Faith' },
  { book: 'isaiah', chapter: '41', verse: '10', category: 'Strength' },
  { book: 'psalms', chapter: '46', verse: '1', category: 'Comfort' },
  { book: 'matthew', chapter: '6', verse: '33', category: 'Faith' },
  { book: 'philippians', chapter: '4', verse: '6', category: 'Comfort' },
  { book: '1 corinthians', chapter: '13', verse: '4', category: 'Love' },
  { book: '1 corinthians', chapter: '13', verse: '13', category: 'Love' },
  { book: 'psalms', chapter: '34', verse: '18', category: 'Comfort' },
  { book: 'isaiah', chapter: '40', verse: '31', category: 'Strength' },
  { book: '2 corinthians', chapter: '5', verse: '17', category: 'Salvation' },
  { book: '1 john', chapter: '4', verse: '19', category: 'Love' },
  { book: '1 peter', chapter: '5', verse: '7', category: 'Comfort' },
  { book: 'hebrews', chapter: '11', verse: '1', category: 'Faith' },
  { book: 'hebrews', chapter: '11', verse: '6', category: 'Faith' },
  { book: 'joshua', chapter: '1', verse: '9', category: 'Strength' },
  { book: 'matthew', chapter: '11', verse: '28', category: 'Comfort' },
  { book: 'romans', chapter: '15', verse: '13', category: 'Hope' },
  { book: 'psalms', chapter: '37', verse: '4', category: 'Faith' },
  { book: 'galatians', chapter: '5', verse: '22', category: 'Love' },
  { book: 'ephesians', chapter: '2', verse: '8', category: 'Salvation' },
  { book: 'psalms', chapter: '91', verse: '1', category: 'Comfort' },
  { book: 'romans', chapter: '12', verse: '2', category: 'Faith' },
  { book: 'colossians', chapter: '3', verse: '23', category: 'Strength' },
  { book: '1 thessalonians', chapter: '5', verse: '16', category: 'Hope' },
  { book: 'psalms', chapter: '19', verse: '14', category: 'Faith' },
  { book: 'matthew', chapter: '5', verse: '16', category: 'Love' },
  { book: 'john', chapter: '14', verse: '6', category: 'Salvation' },
  { book: 'acts', chapter: '1', verse: '8', category: 'Strength' },
  { book: 'psalms', chapter: '27', verse: '1', category: 'Strength' },
  { book: 'isaiah', chapter: '53', verse: '5', category: 'Salvation' },
  { book: 'romans', chapter: '6', verse: '23', category: 'Salvation' },
  { book: '2 timothy', chapter: '1', verse: '7', category: 'Strength' },
  { book: 'psalms', chapter: '119', verse: '105', category: 'Faith' },
  { book: 'matthew', chapter: '28', verse: '19', category: 'Strength' },
  { book: 'john', chapter: '1', verse: '1', category: 'Faith' },
  { book: 'romans', chapter: '5', verse: '8', category: 'Love' },
  { book: 'ephesians', chapter: '6', verse: '11', category: 'Strength' },
  { book: 'psalms', chapter: '51', verse: '10', category: 'Faith' },
  { book: 'hebrews', chapter: '13', verse: '8', category: 'Faith' },
  { book: '1 john', chapter: '1', verse: '9', category: 'Salvation' },
  { book: 'psalms', chapter: '121', verse: '1', category: 'Comfort' },
  { book: 'matthew', chapter: '7', verse: '7', category: 'Faith' },
  { book: 'john', chapter: '15', verse: '5', category: 'Faith' },
  { book: 'james', chapter: '1', verse: '2', category: 'Hope' },
  { book: 'psalms', chapter: '23', verse: '4', category: 'Comfort' },
  { book: 'isaiah', chapter: '43', verse: '2', category: 'Comfort' },
  { book: 'romans', chapter: '8', verse: '38', category: 'Love' },
  { book: 'galatians', chapter: '2', verse: '20', category: 'Faith' },
  { book: 'psalms', chapter: '139', verse: '14', category: 'Hope' },
  { book: 'matthew', chapter: '6', verse: '34', category: 'Comfort' },
  { book: 'john', chapter: '8', verse: '32', category: 'Faith' },
  { book: '2 corinthians', chapter: '4', verse: '18', category: 'Hope' },
  { book: 'psalms', chapter: '62', verse: '1', category: 'Faith' },
  { book: 'philippians', chapter: '1', verse: '6', category: 'Hope' },
  { book: 'ephesians', chapter: '3', verse: '20', category: 'Strength' },
  { book: '1 peter', chapter: '2', verse: '24', category: 'Salvation' },
  { book: 'psalms', chapter: '16', verse: '11', category: 'Hope' },
  { book: 'matthew', chapter: '11', verse: '29', category: 'Comfort' },
  { book: 'john', chapter: '10', verse: '10', category: 'Hope' },
  { book: 'romans', chapter: '8', verse: '1', category: 'Salvation' },
  { book: 'isaiah', chapter: '55', verse: '8', category: 'Faith' },
  { book: 'psalms', chapter: '34', verse: '8', category: 'Faith' },
  { book: 'hebrews', chapter: '4', verse: '16', category: 'Faith' },
  { book: 'james', chapter: '4', verse: '7', category: 'Strength' },
  { book: '1 john', chapter: '4', verse: '8', category: 'Love' },
  { book: 'psalms', chapter: '145', verse: '18', category: 'Faith' },
  { book: 'matthew', chapter: '5', verse: '9', category: 'Love' },
  { book: 'mark', chapter: '11', verse: '24', category: 'Faith' },
  { book: '2 peter', chapter: '3', verse: '9', category: 'Hope' },
  { book: 'psalms', chapter: '103', verse: '8', category: 'Love' },
  { book: 'luke', chapter: '6', verse: '31', category: 'Love' },
  { book: 'colossians', chapter: '3', verse: '13', category: 'Love' },
  { book: '1 thessalonians', chapter: '5', verse: '11', category: 'Comfort' },
  { book: 'psalms', chapter: '147', verse: '3', category: 'Healing' },
  { book: 'jeremiah', chapter: '30', verse: '17', category: 'Healing' },
  { book: 'isaiah', chapter: '41', verse: '13', category: 'Comfort' },
  { book: 'psalms', chapter: '107', verse: '20', category: 'Healing' },
  { book: 'matthew', chapter: '9', verse: '22', category: 'Healing' },
  { book: 'james', chapter: '5', verse: '15', category: 'Healing' },
  { book: '1 peter', chapter: '5', verse: '10', category: 'Strength' },
  { book: 'psalms', chapter: '30', verse: '2', category: 'Healing' },
  { book: 'proverbs', chapter: '17', verse: '22', category: 'Healing' },
  { book: 'isaiah', chapter: '38', verse: '16', category: 'Healing' },
  { book: 'jeremiah', chapter: '33', verse: '6', category: 'Healing' },
  { book: 'psalms', chapter: '41', verse: '3', category: 'Healing' },
  { book: 'matthew', chapter: '4', verse: '23', category: 'Healing' },
  { book: 'malachi', chapter: '4', verse: '2', category: 'Healing' },
  { book: 'psalms', chapter: '103', verse: '3', category: 'Healing' },
  { book: 'exodus', chapter: '15', verse: '26', category: 'Healing' },
  { book: 'deuteronomy', chapter: '31', verse: '6', category: 'Strength' },
  { book: 'psalms', chapter: '18', verse: '2', category: 'Strength' },
  { book: 'nehemiah', chapter: '8', verse: '10', category: 'Strength' },
  { book: 'isaiah', chapter: '12', verse: '2', category: 'Strength' },
  { book: 'psalms', chapter: '28', verse: '7', category: 'Strength' },
  { book: 'habakkuk', chapter: '3', verse: '19', category: 'Strength' },
  { book: 'ephesians', chapter: '6', verse: '10', category: 'Strength' },
  { book: '1 chronicles', chapter: '16', verse: '11', category: 'Strength' },
  { book: 'psalms', chapter: '73', verse: '26', category: 'Strength' },
  { book: '2 samuel', chapter: '22', verse: '33', category: 'Strength' },
  { book: 'isaiah', chapter: '26', verse: '4', category: 'Strength' },
  { book: 'psalms', chapter: '29', verse: '11', category: 'Strength' },
  { book: 'zechariah', chapter: '4', verse: '6', category: 'Strength' },
  { book: 'matthew', chapter: '19', verse: '26', category: 'Faith' },
  { book: 'mark', chapter: '9', verse: '23', category: 'Faith' },
  { book: 'luke', chapter: '1', verse: '37', category: 'Faith' },
  { book: 'romans', chapter: '1', verse: '17', category: 'Faith' },
  { book: 'galatians', chapter: '5', verse: '6', category: 'Faith' },
  { book: 'ephesians', chapter: '2', verse: '8', category: 'Faith' },
  { book: 'hebrews', chapter: '12', verse: '2', category: 'Faith' },
  { book: 'james', chapter: '1', verse: '6', category: 'Faith' },
  { book: '1 john', chapter: '5', verse: '4', category: 'Faith' },
  { book: 'romans', chapter: '10', verse: '17', category: 'Faith' },
  { book: 'matthew', chapter: '17', verse: '20', category: 'Faith' },
  { book: 'mark', chapter: '5', verse: '34', category: 'Faith' },
  { book: 'luke', chapter: '17', verse: '5', category: 'Faith' },
  { book: '2 corinthians', chapter: '5', verse: '7', category: 'Faith' },
  { book: 'colossians', chapter: '2', verse: '7', category: 'Faith' },
  { book: '1 timothy', chapter: '6', verse: '12', category: 'Faith' },
  { book: '2 timothy', chapter: '4', verse: '7', category: 'Faith' },
  { book: 'hebrews', chapter: '11', verse: '7', category: 'Faith' },
  { book: 'james', chapter: '2', verse: '17', category: 'Faith' },
  { book: 'matthew', chapter: '21', verse: '21', category: 'Faith' },
  { book: 'john', chapter: '20', verse: '29', category: 'Faith' },
  { book: 'acts', chapter: '16', verse: '31', category: 'Salvation' },
  { book: 'romans', chapter: '10', verse: '9', category: 'Salvation' },
  { book: 'ephesians', chapter: '1', verse: '7', category: 'Salvation' },
  { book: 'titus', chapter: '3', verse: '5', category: 'Salvation' },
  { book: '1 peter', chapter: '1', verse: '18', category: 'Salvation' },
  { book: 'revelation', chapter: '3', verse: '20', category: 'Salvation' },
  { book: 'john', chapter: '5', verse: '24', category: 'Salvation' },
  { book: 'acts', chapter: '2', verse: '21', category: 'Salvation' },
  { book: 'romans', chapter: '5', verse: '1', category: 'Salvation' },
  { book: '1 corinthians', chapter: '15', verse: '22', category: 'Salvation' },
  { book: '2 corinthians', chapter: '5', verse: '21', category: 'Salvation' },
  { book: 'galatians', chapter: '3', verse: '13', category: 'Salvation' },
  { book: 'ephesians', chapter: '2', verse: '5', category: 'Salvation' },
  { book: 'philippians', chapter: '3', verse: '20', category: 'Salvation' },
  { book: 'colossians', chapter: '1', verse: '13', category: 'Salvation' },
  { book: '1 thessalonians', chapter: '5', verse: '9', category: 'Salvation' },
  { book: '2 timothy', chapter: '1', verse: '10', category: 'Salvation' },
  { book: 'hebrews', chapter: '7', verse: '25', category: 'Salvation' },
  { book: '1 john', chapter: '2', verse: '2', category: 'Salvation' },
  { book: 'revelation', chapter: '7', verse: '10', category: 'Salvation' },
  { book: 'john', chapter: '3', verse: '17', category: 'Love' },
  { book: 'romans', chapter: '5', verse: '5', category: 'Love' },
  { book: '1 john', chapter: '3', verse: '1', category: 'Love' },
  { book: '1 john', chapter: '4', verse: '16', category: 'Love' },
  { book: '1 john', chapter: '4', verse: '18', category: 'Love' },
  { book: 'ephesians', chapter: '5', verse: '2', category: 'Love' },
  { book: '1 peter', chapter: '4', verse: '8', category: 'Love' },
  { book: '1 john', chapter: '3', verse: '18', category: 'Love' },
  { book: 'john', chapter: '13', verse: '34', category: 'Love' },
  { book: 'john', chapter: '15', verse: '13', category: 'Love' },
  { book: 'romans', chapter: '8', verse: '35', category: 'Love' },
  { book: 'song of solomon', chapter: '8', verse: '7', category: 'Love' },
  { book: '1 corinthians', chapter: '16', verse: '14', category: 'Love' },
  { book: 'colossians', chapter: '3', verse: '14', category: 'Love' },
  { book: '1 thessalonians', chapter: '3', verse: '12', category: 'Love' },
  { book: '1 john', chapter: '3', verse: '16', category: 'Love' },
  { book: 'psalms', chapter: '36', verse: '7', category: 'Love' },
  { book: 'psalms', chapter: '63', verse: '3', category: 'Love' },
  { book: 'isaiah', chapter: '54', verse: '10', category: 'Love' },
  { book: 'lamentations', chapter: '3', verse: '22', category: 'Love' },
  { book: 'psalms', chapter: '86', verse: '15', category: 'Love' },
  { book: 'romans', chapter: '12', verse: '9', category: 'Love' },
  { book: 'hebrews', chapter: '6', verse: '10', category: 'Love' },
  { book: '1 john', chapter: '4', verse: '11', category: 'Love' },
  { book: 'john', chapter: '14', verse: '15', category: 'Love' },
  { book: 'psalms', chapter: '42', verse: '11', category: 'Hope' },
  { book: 'romans', chapter: '4', verse: '18', category: 'Hope' },
  { book: 'romans', chapter: '8', verse: '24', category: 'Hope' },
  { book: 'romans', chapter: '12', verse: '12', category: 'Hope' },
  { book: '1 corinthians', chapter: '13', verse: '13', category: 'Hope' },
  { book: 'colossians', chapter: '1', verse: '27', category: 'Hope' },
  { book: '1 thessalonians', chapter: '4', verse: '13', category: 'Hope' },
  { book: 'hebrews', chapter: '6', verse: '19', category: 'Hope' },
  { book: '1 peter', chapter: '1', verse: '3', category: 'Hope' },
  { book: '1 peter', chapter: '3', verse: '15', category: 'Hope' },
  { book: 'psalms', chapter: '71', verse: '14', category: 'Hope' },
  { book: 'psalms', chapter: '78', verse: '7', category: 'Hope' },
  { book: 'proverbs', chapter: '23', verse: '18', category: 'Hope' },
  { book: 'isaiah', chapter: '49', verse: '23', category: 'Hope' },
  { book: 'jeremiah', chapter: '17', verse: '7', category: 'Hope' },
  { book: 'lamentations', chapter: '3', verse: '24', category: 'Hope' },
  { book: 'micah', chapter: '7', verse: '7', category: 'Hope' },
  { book: 'zechariah', chapter: '9', verse: '12', category: 'Hope' },
  { book: 'acts', chapter: '24', verse: '15', category: 'Hope' },
  { book: 'romans', chapter: '5', verse: '2', category: 'Hope' },
  { book: 'romans', chapter: '15', verse: '4', category: 'Hope' },
  { book: 'galatians', chapter: '5', verse: '5', category: 'Hope' },
  { book: 'ephesians', chapter: '1', verse: '18', category: 'Hope' },
  { book: 'ephesians', chapter: '4', verse: '4', category: 'Hope' },
  { book: 'philippians', chapter: '3', verse: '14', category: 'Hope' },
  { book: 'colossians', chapter: '1', verse: '5', category: 'Hope' },
  { book: '2 thessalonians', chapter: '2', verse: '16', category: 'Hope' },
  { book: '1 timothy', chapter: '1', verse: '1', category: 'Hope' },
  { book: 'titus', chapter: '1', verse: '2', category: 'Hope' },
  { book: 'titus', chapter: '2', verse: '13', category: 'Hope' },
  { book: 'hebrews', chapter: '10', verse: '23', category: 'Hope' },
  { book: '1 peter', chapter: '1', verse: '21', category: 'Hope' },
  { book: '1 john', chapter: '3', verse: '3', category: 'Hope' },
  { book: 'psalms', chapter: '9', verse: '9', category: 'Comfort' },
  { book: 'psalms', chapter: '23', verse: '4', category: 'Comfort' },
  { book: 'psalms', chapter: '34', verse: '18', category: 'Comfort' },
  { book: 'psalms', chapter: '46', verse: '1', category: 'Comfort' },
  { book: 'psalms', chapter: '55', verse: '22', category: 'Comfort' },
  { book: 'psalms', chapter: '71', verse: '21', category: 'Comfort' },
  { book: 'psalms', chapter: '94', verse: '19', category: 'Comfort' },
  { book: 'isaiah', chapter: '25', verse: '8', category: 'Comfort' },
  { book: 'isaiah', chapter: '40', verse: '1', category: 'Comfort' },
  { book: 'isaiah', chapter: '51', verse: '12', category: 'Comfort' },
  { book: 'isaiah', chapter: '66', verse: '13', category: 'Comfort' },
  { book: 'matthew', chapter: '5', verse: '4', category: 'Comfort' },
  { book: 'matthew', chapter: '11', verse: '28', category: 'Comfort' },
  { book: 'john', chapter: '14', verse: '1', category: 'Comfort' },
  { book: 'john', chapter: '14', verse: '27', category: 'Comfort' },
  { book: 'john', chapter: '16', verse: '33', category: 'Comfort' },
  { book: 'acts', chapter: '9', verse: '31', category: 'Comfort' },
  { book: 'romans', chapter: '8', verse: '26', category: 'Comfort' },
  { book: '2 corinthians', chapter: '1', verse: '3', category: 'Comfort' },
  { book: '2 corinthians', chapter: '1', verse: '4', category: 'Comfort' },
  { book: '2 thessalonians', chapter: '2', verse: '16', category: 'Comfort' },
  { book: 'psalms', chapter: '116', verse: '15', category: 'Comfort' },
  { book: 'psalms', chapter: '30', verse: '5', category: 'Comfort' },
  { book: 'psalms', chapter: '13', verse: '5', category: 'Comfort' },
  { book: '2 corinthians', chapter: '7', verse: '6', category: 'Comfort' },
  { book: 'genesis', chapter: '28', verse: '15', category: 'Comfort' },
  { book: 'deuteronomy', chapter: '33', verse: '27', category: 'Comfort' },
  { book: 'joshua', chapter: '1', verse: '5', category: 'Comfort' },
  { book: '1 kings', chapter: '8', verse: '57', category: 'Comfort' },
  { book: '1 chronicles', chapter: '28', verse: '20', category: 'Comfort' },
  { book: 'psalms', chapter: '9', verse: '10', category: 'Comfort' },
  { book: 'psalms', chapter: '31', verse: '24', category: 'Comfort' },
  { book: 'psalms', chapter: '138', verse: '7', category: 'Comfort' },
  { book: 'isaiah', chapter: '12', verse: '1', category: 'Comfort' },
  { book: 'isaiah', chapter: '26', verse: '3', category: 'Comfort' },
  { book: 'isaiah', chapter: '30', verse: '15', category: 'Comfort' },
  { book: 'nahum', chapter: '1', verse: '7', category: 'Comfort' },
  { book: 'matthew', chapter: '6', verse: '25', category: 'Comfort' },
  { book: 'luke', chapter: '12', verse: '32', category: 'Comfort' },
  { book: 'john', chapter: '14', verse: '18', category: 'Comfort' },
  { book: '2 corinthians', chapter: '4', verse: '17', category: 'Comfort' },
  { book: 'philippians', chapter: '4', verse: '7', category: 'Comfort' },
  { book: '2 thessalonians', chapter: '3', verse: '16', category: 'Comfort' },
  { book: '2 timothy', chapter: '4', verse: '17', category: 'Comfort' },
  { book: 'hebrews', chapter: '13', verse: '5', category: 'Comfort' },
  { book: '1 peter', chapter: '5', verse: '7', category: 'Comfort' },
  { book: 'revelation', chapter: '21', verse: '4', category: 'Comfort' },
  { book: 'genesis', chapter: '1', verse: '1', category: 'Faith' },
  { book: 'exodus', chapter: '14', verse: '14', category: 'Strength' },
  { book: 'leviticus', chapter: '19', verse: '18', category: 'Love' },
  { book: 'numbers', chapter: '6', verse: '24', category: 'Comfort' },
  { book: 'deuteronomy', chapter: '6', verse: '5', category: 'Love' },
  { book: 'joshua', chapter: '24', verse: '15', category: 'Faith' },
  { book: 'judges', chapter: '6', verse: '16', category: 'Strength' },
  { book: 'ruth', chapter: '1', verse: '16', category: 'Love' },
  { book: '1 samuel', chapter: '16', verse: '7', category: 'Faith' },
  { book: '2 samuel', chapter: '7', verse: '22', category: 'Faith' },
  { book: '1 kings', chapter: '3', verse: '9', category: 'Faith' },
  { book: '2 kings', chapter: '6', verse: '16', category: 'Strength' },
  { book: 'ezra', chapter: '7', verse: '10', category: 'Faith' },
  { book: 'nehemiah', chapter: '4', verse: '14', category: 'Strength' },
  { book: 'esther', chapter: '4', verse: '14', category: 'Hope' },
  { book: 'job', chapter: '19', verse: '25', category: 'Faith' },
  { book: 'job', chapter: '42', verse: '2', category: 'Faith' },
  { book: 'psalms', chapter: '1', verse: '1', category: 'Faith' },
  { book: 'psalms', chapter: '5', verse: '3', category: 'Faith' },
  { book: 'psalms', chapter: '19', verse: '1', category: 'Faith' },
  { book: 'psalms', chapter: '22', verse: '1', category: 'Comfort' },
  { book: 'psalms', chapter: '37', verse: '5', category: 'Faith' },
  { book: 'psalms', chapter: '40', verse: '1', category: 'Hope' },
  { book: 'psalms', chapter: '46', verse: '10', category: 'Comfort' },
  { book: 'psalms', chapter: '50', verse: '15', category: 'Faith' },
  { book: 'psalms', chapter: '56', verse: '3', category: 'Faith' },
  { book: 'psalms', chapter: '66', verse: '20', category: 'Faith' },
  { book: 'psalms', chapter: '100', verse: '4', category: 'Faith' },
  { book: 'psalms', chapter: '118', verse: '24', category: 'Hope' },
  { book: 'psalms', chapter: '119', verse: '71', category: 'Faith' },
  { book: 'psalms', chapter: '121', verse: '2', category: 'Strength' },
  { book: 'psalms', chapter: '127', verse: '1', category: 'Faith' },
  { book: 'psalms', chapter: '133', verse: '1', category: 'Love' },
  { book: 'psalms', chapter: '150', verse: '6', category: 'Faith' },
  { book: 'proverbs', chapter: '1', verse: '7', category: 'Faith' },
  { book: 'proverbs', chapter: '4', verse: '23', category: 'Strength' },
  { book: 'proverbs', chapter: '16', verse: '3', category: 'Faith' },
  { book: 'proverbs', chapter: '22', verse: '6', category: 'Faith' },
  { book: 'proverbs', chapter: '27', verse: '17', category: 'Strength' },
  { book: 'ecclesiastes', chapter: '3', verse: '1', category: 'Faith' },
  { book: 'ecclesiastes', chapter: '12', verse: '13', category: 'Faith' },
  { book: 'song of solomon', chapter: '2', verse: '4', category: 'Love' },
  { book: 'isaiah', chapter: '9', verse: '6', category: 'Salvation' },
  { book: 'isaiah', chapter: '11', verse: '2', category: 'Faith' },
  { book: 'isaiah', chapter: '53', verse: '4', category: 'Healing' },
  { book: 'isaiah', chapter: '58', verse: '11', category: 'Strength' },
  { book: 'isaiah', chapter: '61', verse: '1', category: 'Hope' },
  { book: 'isaiah', chapter: '64', verse: '8', category: 'Faith' },
  { book: 'jeremiah', chapter: '1', verse: '5', category: 'Hope' },
  { book: 'jeremiah', chapter: '15', verse: '16', category: 'Faith' },
  { book: 'jeremiah', chapter: '17', verse: '14', category: 'Healing' },
  { book: 'jeremiah', chapter: '31', verse: '3', category: 'Love' },
  { book: 'ezekiel', chapter: '36', verse: '26', category: 'Salvation' },
  { book: 'daniel', chapter: '3', verse: '17', category: 'Faith' },
  { book: 'daniel', chapter: '6', verse: '27', category: 'Strength' },
  { book: 'hosea', chapter: '6', verse: '6', category: 'Love' },
  { book: 'joel', chapter: '2', verse: '28', category: 'Hope' },
  { book: 'amos', chapter: '5', verse: '24', category: 'Faith' },
  { book: 'obadiah', chapter: '1', verse: '21', category: 'Salvation' },
  { book: 'jonah', chapter: '2', verse: '7', category: 'Salvation' },
  { book: 'micah', chapter: '6', verse: '8', category: 'Love' },
  { book: 'habakkuk', chapter: '2', verse: '4', category: 'Faith' },
  { book: 'zephaniah', chapter: '3', verse: '17', category: 'Love' },
  { book: 'haggai', chapter: '2', verse: '4', category: 'Strength' },
  { book: 'zechariah', chapter: '8', verse: '13', category: 'Hope' },
  { book: 'malachi', chapter: '3', verse: '6', category: 'Faith' },
  { book: 'matthew', chapter: '1', verse: '23', category: 'Salvation' },
  { book: 'matthew', chapter: '4', verse: '4', category: 'Faith' },
  { book: 'matthew', chapter: '10', verse: '32', category: 'Faith' },
  { book: 'matthew', chapter: '16', verse: '24', category: 'Faith' },
  { book: 'matthew', chapter: '22', verse: '37', category: 'Love' },
  { book: 'matthew', chapter: '24', verse: '14', category: 'Hope' },
  { book: 'mark', chapter: '1', verse: '15', category: 'Salvation' },
  { book: 'mark', chapter: '6', verse: '50', category: 'Comfort' },
  { book: 'mark', chapter: '12', verse: '30', category: 'Love' },
  { book: 'mark', chapter: '16', verse: '15', category: 'Strength' },
  { book: 'luke', chapter: '2', verse: '11', category: 'Salvation' },
  { book: 'luke', chapter: '6', verse: '38', category: 'Love' },
  { book: 'luke', chapter: '11', verse: '9', category: 'Faith' },
  { book: 'luke', chapter: '19', verse: '10', category: 'Salvation' },
  { book: 'luke', chapter: '24', verse: '47', category: 'Salvation' },
  { book: 'john', chapter: '1', verse: '14', category: 'Faith' },
  { book: 'john', chapter: '3', verse: '3', category: 'Salvation' },
  { book: 'john', chapter: '4', verse: '24', category: 'Faith' },
  { book: 'john', chapter: '6', verse: '35', category: 'Faith' },
  { book: 'john', chapter: '8', verse: '12', category: 'Faith' },
  { book: 'john', chapter: '11', verse: '25', category: 'Hope' },
  { book: 'john', chapter: '13', verse: '1', category: 'Love' },
  { book: 'john', chapter: '16', verse: '13', category: 'Faith' },
  { book: 'john', chapter: '17', verse: '17', category: 'Faith' },
  { book: 'acts', chapter: '1', verse: '11', category: 'Hope' },
  { book: 'acts', chapter: '4', verse: '12', category: 'Salvation' },
  { book: 'acts', chapter: '17', verse: '11', category: 'Faith' },
  { book: 'acts', chapter: '20', verse: '35', category: 'Love' },
  { book: 'romans', chapter: '3', verse: '23', category: 'Salvation' },
  { book: 'romans', chapter: '5', verse: '10', category: 'Salvation' },
  { book: 'romans', chapter: '8', verse: '11', category: 'Strength' },
  { book: 'romans', chapter: '9', verse: '16', category: 'Faith' },
  { book: 'romans', chapter: '11', verse: '36', category: 'Faith' },
  { book: 'romans', chapter: '13', verse: '10', category: 'Love' },
  { book: 'romans', chapter: '15', verse: '1', category: 'Strength' },
  { book: '1 corinthians', chapter: '2', verse: '9', category: 'Hope' },
  { book: '1 corinthians', chapter: '3', verse: '16', category: 'Faith' },
  { book: '1 corinthians', chapter: '10', verse: '13', category: 'Strength' },
  { book: '1 corinthians', chapter: '15', verse: '58', category: 'Strength' },
  { book: '2 corinthians', chapter: '2', verse: '14', category: 'Hope' },
  { book: '2 corinthians', chapter: '5', verse: '15', category: 'Love' },
  { book: '2 corinthians', chapter: '9', verse: '7', category: 'Love' },
  { book: 'galatians', chapter: '1', verse: '10', category: 'Faith' },
  { book: 'galatians', chapter: '5', verse: '1', category: 'Salvation' },
  { book: 'galatians', chapter: '6', verse: '2', category: 'Love' },
  { book: 'galatians', chapter: '6', verse: '9', category: 'Hope' },
  { book: 'ephesians', chapter: '1', verse: '3', category: 'Faith' },
  { book: 'ephesians', chapter: '2', verse: '10', category: 'Faith' },
  { book: 'ephesians', chapter: '4', verse: '32', category: 'Love' },
  { book: 'ephesians', chapter: '5', verse: '8', category: 'Faith' },
  { book: 'ephesians', chapter: '6', verse: '12', category: 'Strength' },
  { book: 'philippians', chapter: '2', verse: '5', category: 'Faith' },
  { book: 'philippians', chapter: '3', verse: '8', category: 'Faith' },
  { book: 'philippians', chapter: '4', verse: '8', category: 'Faith' },
  { book: 'colossians', chapter: '1', verse: '11', category: 'Strength' },
  { book: 'colossians', chapter: '3', verse: '1', category: 'Faith' },
  { book: '1 thessalonians', chapter: '4', verse: '7', category: 'Faith' },
  { book: '2 thessalonians', chapter: '3', verse: '3', category: 'Strength' },
  { book: '1 timothy', chapter: '4', verse: '12', category: 'Strength' },
  { book: '2 timothy', chapter: '2', verse: '15', category: 'Faith' },
  { book: '2 timothy', chapter: '3', verse: '16', category: 'Faith' },
  { book: 'titus', chapter: '3', verse: '8', category: 'Faith' },
  { book: 'philemon', chapter: '1', verse: '6', category: 'Faith' },
  { book: 'hebrews', chapter: '3', verse: '13', category: 'Love' },
  { book: 'hebrews', chapter: '10', verse: '25', category: 'Love' },
  { book: 'hebrews', chapter: '11', verse: '8', category: 'Faith' },
  { book: 'james', chapter: '1', verse: '12', category: 'Hope' },
  { book: 'james', chapter: '3', verse: '17', category: 'Faith' },
  { book: 'james', chapter: '5', verse: '16', category: 'Faith' },
  { book: '1 peter', chapter: '1', verse: '15', category: 'Faith' },
  { book: '1 peter', chapter: '4', verse: '16', category: 'Faith' },
  { book: '2 peter', chapter: '1', verse: '5', category: 'Faith' },
  { book: '1 john', chapter: '2', verse: '15', category: 'Faith' },
  { book: '1 john', chapter: '3', verse: '22', category: 'Faith' },
  { book: '2 john', chapter: '1', verse: '6', category: 'Love' },
  { book: '3 john', chapter: '1', verse: '4', category: 'Faith' },
  { book: 'jude', chapter: '1', verse: '24', category: 'Strength' },
  { book: 'revelation', chapter: '1', verse: '8', category: 'Faith' },
  { book: 'revelation', chapter: '3', verse: '5', category: 'Salvation' },
  { book: 'revelation', chapter: '21', verse: '6', category: 'Hope' },
  { book: 'revelation', chapter: '22', verse: '13', category: 'Faith' },
];

/**
 * Get the day of year (1-366).
 */
export function getDayOfYear(): number {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  return Math.floor(diff / (1000 * 60 * 60 * 24));
}

/**
 * Get today's verse entry based on day of year.
 */
export function getDailyVerseEntry(): DailyVerseEntry {
  const dayOfYear = getDayOfYear();
  return dailyVerses[dayOfYear % dailyVerses.length];
}
